# Generated by Django 5.0.6 on 2024-07-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_modelo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelo",
            options={"verbose_name": "Modelo", "verbose_name_plural": "Modelos"},
        ),
    ]
